language: node_js
node_js:
- 6.10.0
notifications:
  email: false
  webhooks: https://ambrosio-tele.herokuapp.com/sacarinobot/travisci/133188453
  on_success: always
  on_failure: always
  on_start: always
before_script:
- npm install -g grunt-cli
deploy:
  api_key:
    secure: "GwP7FUn2hRo1qlGx/mQHI7lV30OkNQhN2FYuo+eOWcM8YYrCFMMEgS6N0eUqeoMw+CMto6/Qf0MTeYsepZT7BV/4PKiiozddOPotNY/eXTzoJBs7TgPwKz0GHnNOrRZdK9dz6dKi4rPwkwBaj4g7AWiEFkxojw/CMArLDSXR+oLIypCqOoBEwC6PUl4XhSzrvdJlOKYhdLe9dDG/WD6ntxpRupWmozMqwimHxrbxtTTCCnDr7xllFahST1LAF1Vhj6eaOJz/hwWjilQcUfSZHJ/dT1RxMcmedPmxqCxoJpjMMVRREpnBbkPOijEro5E5aAQq2XF9Gx6m8MuT1xc6LTz8hvog6EvnZTtt21Z/Jh6+GFCFN07ojan3lDmZfMFAk4QlUCucPhPFTgAzOvRo95aVfaWj6RMfKt9bGJs1UsU9NVWXw6RMN3yI685JyXi/n7qsiDVLUvIm5fcIA4ii/8RAPbCS0m1X7ao8W/4w8yVJV8X/hQjA+o2UxHL3rKJg/p2qXjVND9rNC1bfljxAqVx0LrWSOn1N3425bgcWAir6YFSXvwx4z+GxO1b542q8p9yzUI6SbI9s3RVGWAu9N9j3S+Xy84o3zrE+9zxBwuY1xMXwxwPCeI8+EezocgAUL4eg6btU+RjtUCW30bZsQtONvuzp1vExRsh4nf3oOXs="
  email:
    secure: "g7s2HzNbP0i1wid5quAiNOtIVxr7BiBW8UaoN7qrs/yJWn5THcU+pLvUCn/yEkKn0JDU365WYi+iDILBwwIHfOqOMdy9e7PTbftIkqeIrKz0u7CAfexYtTSDVVvisK7RSQ9T2Ld3pMWRWIAQRZ/f5bgsJUZyf7NhUyB/OY7bqoKd2ux8Em7c8vbuOd5s0KnDQNGkwC08ngLOniFaoGR0kIWPAHAcuhLKgV/ITpBQbl0E3u7HjGP0aC/7b9Hcr3EszsAacuZWqNaG5SDLqmBHx1Um4GmoLt10BrJtlBKKB/hE46lIYXN2qN09pWCH//gnHITMy7KVqMCoULhs6ABNtF4Ui+LMXyq7UqzO3/7SCIqTNJ40adazL+/FYBJNPETvl044INLxf4e49fnONzQMTSl4+AkJlUfU53LllWDK20MPiSdHJup64y+Xtd6CEHelvcLFwEm/arSAm7PWFLG/P+D10gaiTaOWSxYQbPbsSX2bgUK1hHS6s3Yy9+Ka3zXfZg7EQbYwipniKUpT7+OxD5Z5ThahD2E85LF7Fk5CUZRiPsby5LV+FfNgWMd8CS5OrlUbBrvLgWO2OcHUQVy6QQGXkJ9oE1f68l2ZrY/t8pWD/+dwzI7Dof2fksCVEfl5fsHiQYxTbPHjSx7mu0LGoGLUg3JBbnHWQ7+LEop0mQw="
  provider: npm
